/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        'background': '#0b1326',
        'surface': '#0b1326',
        'surface-dim': '#0b1326',
        'surface-container-lowest': '#060e20',
        'surface-container-low': '#131b2e',
        'surface-container': '#171f33',
        'surface-container-high': '#222a3d',
        'surface-container-highest': '#2d3449',
        'surface-bright': '#31394d',
        'surface-variant': '#2d3449',
        'surface-tint': '#4fdbc8',
        'on-surface': '#dae2fd',
        'on-surface-variant': '#bbcac6',
        'on-background': '#dae2fd',
        'primary': '#4fdbc8',
        'primary-container': '#14b8a6',
        'primary-fixed': '#71f8e4',
        'primary-fixed-dim': '#4fdbc8',
        'on-primary': '#003731',
        'on-primary-container': '#00423b',
        'on-primary-fixed': '#00201c',
        'on-primary-fixed-variant': '#005048',
        'secondary': '#ffb95f',
        'secondary-container': '#ee9800',
        'secondary-fixed': '#ffddb8',
        'secondary-fixed-dim': '#ffb95f',
        'on-secondary': '#472a00',
        'on-secondary-container': '#5b3800',
        'on-secondary-fixed': '#2a1700',
        'on-secondary-fixed-variant': '#653e00',
        'tertiary': '#7bd0ff',
        'tertiary-container': '#1eb0ea',
        'tertiary-fixed': '#c4e7ff',
        'tertiary-fixed-dim': '#7bd0ff',
        'on-tertiary': '#00354a',
        'on-tertiary-container': '#003f58',
        'on-tertiary-fixed': '#001e2c',
        'on-tertiary-fixed-variant': '#004c69',
        'outline': '#859490',
        'outline-variant': '#3c4947',
        'error': '#ffb4ab',
        'error-container': '#93000a',
        'on-error': '#690005',
        'on-error-container': '#ffdad6',
        'inverse-surface': '#dae2fd',
        'inverse-on-surface': '#283044',
        'inverse-primary': '#006b5f',
      },
      fontFamily: {
        'headline': ['"Space Grotesk"', 'sans-serif'],
        'body': ['Inter', 'sans-serif'],
        'label': ['Inter', 'sans-serif'],
      },
    },
  },
  plugins: [],
}
